project_id = "hdvjxlirfexofomkmwqc"

[functions.ceo-pin]
verify_jwt = true

[functions.passkey-register-options]
verify_jwt = false

[functions.passkey-register-verify]
verify_jwt = false

[functions.passkey-auth-options]
verify_jwt = false

[functions.passkey-auth-verify]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.send-order-notification]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.send-meeting-invite]
verify_jwt = true

[functions.send-task-notification]
verify_jwt = true

[functions.send-shipping-notification]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-password-reset-otp]
verify_jwt = false

[functions.send-order-cancellation]
verify_jwt = true
